更新部分章节到 Swift 5.5
SwiftGGTeam/the-swift-programming-language-in-chinese pull request #1152
Opened 2021-07-05 06:17 UTC by Nemocdz

#1114 
#1124 
#1126

2021-07-08 16:10 UTC, WAMaker requested changes

2021-07-08 16:10 UTC, WAMaker commented on source/02_language_guide/27_Advanced_Operators.md
> +代码一切正常，但是不够优雅。`AllCaps` 后面的括号嵌套太深，可读性不佳。`name` 为 `nil` 时使用 “World” 的兜底逻辑必须要依赖 `??` 操作符，这在逻辑更复杂的时候会更难以阅读。如果还需要 `switch` 或者 `for` 循环来构建绘制的一部分，就更难以编写了。使用结果构造器可以将这样的代码重构得更像普通的 Swift 代码。
这在逻辑更复杂的时候会更难以阅读

第一个更可以去掉

2021-07-09 16:13 UTC, Nemocdz commented
根据校对意见修改

2021-07-11 01:29 UTC, WAMaker approved these changes

2021-07-11 02:14 UTC, merged