Language Reference - Attributes
SwiftGGTeam/the-swift-programming-language-in-chinese pull request #1154
Opened 2021-07-11 15:04 UTC by WAMaker

#1128

2021-07-11 18:58 UTC, numbbbbb requested changes

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +### `resultBuilder` {#resultBuilder}
这里的超链接id和其他保持一致：`#resultBuilder` 改成 `#result-builder`。

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +将该特性应用于类、结构体或者枚举，可以让其成为一个结果构造器。结果构造器能按顺序构造一组嵌套的数据结构。利用它，可以以一种自然的声明式语法为嵌套数据结构实现一套领域专门语言（DSL）。想了解如何使用 `resultBuild`，请参阅 [结果构造器](../02_language_guide/27_Advanced_Operators.md#result-builders)。
这里的超链接，在对应的`27_Advanced_Operators.md`文件里并没有添加，请修改对应文件。

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +结果构造器实现了下面的静态方法。由于所有结果构造器的功能已经通过这些静态方法得以展示，都不需要初始化对应类型的实例。实现 `buildBlock(_:)` 方法是必须的，而那些能让领域专门语言（DSL）拥有额外能力的方法则是可选的。事实上，结果构造器类型的声明不需要遵循任何协议。
由于……，都不需要…… 读起来有点怪，应该是：由于……，因此/所以不需要……
也可以把开头的“由于”删掉，改成：……，因此不需要……。这样比较简洁。

实现 `buildBlock(_:)` 方法是必须的 => `buildBlock(_:)` 方法是必须实现的

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +描述这些静态方法使用了三个类型做占位。`Expression` 为构造器的输入类型，`Component` 为中间结果类型，`FinalResult` 是构造器最终生成结果的类型。将它们替换成你构造器的真正类型。如果构造方法没有为 `Expression` 或 `FinalResult` 指定类型，默认会使用 `Component` 类型。
第一句：这些静态方法的描述中用到了三个类型。

占位符这个我想了下怎么加都不太通顺，“类型占位符”“占位符类型”都很拗口。后面紧跟着就开始解释了，我觉得不加占位符这三个字更好理解一些。

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +    为输入构建一个中间结果。你可以利用它来执行预处理，比如，可以将入参转换为内部类型，或为适用房提供额外的类型推断信息。
这句问题很大，”输入“是翻译错误，”适用房“也是。重新翻译一下。use site意思应该更接近”调用者“或者“使用者”，虽然并不完全准确，如果没有更好的翻译可以用“使用者”。

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +    为输入构建一个中间结果。你可以利用它来执行预处理，比如，可以将入参转换为内部类型，或为适用房提供额外的类型推断信息。
另外原文是”build……from“，并不能翻译成”为“，”为“应该是对应for。

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +    为中间结果构造一个最终结果。你可以返回一个与中间结果不一样的类型最为最终结果，也可以在最终结果返回前对值进行处理。
同上，不应该翻译成”为“。

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +以下的语法转换会递归地将应用了结果构造器语法的代码转换成结果构造器静态方法调用的方式：
这句太长了，读起来很难理解，拆分一下。

下面的语法转换会递归地执行，代码里原本使用了结果构造器语法，会被转换成结果构造器类型的静态方法调用。

并不完美，还是有点难懂，不过结构稍微清晰一点，一遍看下来明白意思。

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +- 如果结果构造器实现了 `buildExpression(_:)` 方法，任何一个表达式都会变成一次方法调用。这种转换是最先发生的。下面的声明方式是一致的：
这种转换是最先发生的 => 这是转换的第一步
下面的声明方式是一致的 => 是等价的

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +- 赋值语句也能像表达式一样被转换，但会被理解为对 () 求值。重载 `buildExpression(_:)` 方法，接收实参类型为 () 来特殊处理赋值。
两个括号加上行内代码样式，和原文一致。

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +- 分支语句检查有效性是通过调用 `buildLimitedAvailability(_:)` 方法实现的。这个转换发生于调用 `buildEither(first:)`、`buildEither(second:)` 或 `buildOptional(_:)` 之前。使用 `buildLimitedAvailability(_:)` 方法擦除变更所发生的分支信息。下面的 `buildEither
”擦除变更所发生的分支信息“读不懂意思，重新思考修改。

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +- 分支语句检查有效性是通过调用 `buildLimitedAvailability(_:)` 方法实现的。这个转换发生于调用 `buildEither(first:)`、`buildEither(second:)` 或 `buildOptional(_:)` 之前。使用 `buildLimitedAvailability(_:)` 方法擦除变更所发生的分支信息。下面的 `buildEither
availability并不是有效性，是可用性，判断是否存在。

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +    构建一个中间结果，用于在编译器控制表达式以外传递或擦除类型信息，以进行有效性检查。你可以用它在条件分支中实现类型信息的擦除。
availability并不是有效性，是可用性，判断是否存在。

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +    然而这种方式对于带有代码有效性检验的情况会出现问题：
对于……的情况 读起来很绕，这句话也有点长，拆分。
有效性前面说过了，翻译不正确。

然而如果代码里有可用性判断，这种方式就会产生问题：

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +    上面的代码中，`FutureText` 作为 `brokenDrawing` 类型的一部分出现，因为它是 `DrawEither` 泛型的其中一个类型。如果 `FutureText` 在运行时无效可能引起程序崩溃，即使在这个类型没有被显式调用。
无效翻译错误，不可用。

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +    上面的代码中，`FutureText` 作为 `brokenDrawing` 类型的一部分出现，因为它是 `DrawEither` 泛型的其中一个类型。如果 `FutureText` 在运行时无效可能引起程序崩溃，即使在这个类型没有被显式调用。
最后一句，显式调用，感觉翻译错了。这里explicitly我觉得意思是”明显“，也就是说在这个例子里，虽然FutureText明显没有被使用（因为有available判断的是macOS 99，这个显然是不存在的，也不会执行if语句里的东西），但是还是会导致崩溃。

另外”可能引起程序崩溃“，这里的could应该翻译成”会引起程序崩溃“，并不是表示可能性。

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +- 分支语句会被转换成一连串 `buildEither(first:)` 与 `buildEither(second:)` 的方法调用。语句的场景被映射到了一颗二叉树的叶子结点上，语句则变成了从根节点到叶子结点路径的嵌套 `buildEither` 方法调用。
语句的场景，这里condition并不是场景，是指if else对应的那个判断条件。修改为：语句的不同条件分支被映射到了……。

从根节点到叶子结点路径的嵌套 `buildEither` 方法调用，这个读起来显然是不够通顺的，修改：语句则变成了嵌套调用的 `buildEither` 方法，对应的是二叉树中从根节点到目标叶子节点的路径。

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +    举例来说，如果你的 switch 语句有三种情况，编译器会生成一个拥有 3 个叶子结点的二叉树。同样地，由于从根节点到第二种情况相当于走了"第二个子节点"再到"第一个子节点"这样的路径，就变成了像 `buildEither(first: buildEither(second: ... ))` 这样的嵌套调用。下面的声明方式是一致的：
一致翻译错误，前面说过，修改。

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +- 分支语句不一定会产生值，就像 `if` 语句没有 `else` 闭包时，会变成 `buildOptional(_:)` 调用。如果 `if` 语句满足条件，它的代码块会被转换，作为实参进行传递；否则，`buildOptional(_:)` 会被调用，并用 `nil` 作为它的实参。下面的声明方式是一致的：
一致

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +- 代码块或 `do` 语句会变成 `buildBlock(_:)` 调用。闭包中的语句都会被转换，一次一句，接着它们会变成 `buildBlock(_:)` 方法的参数。下面的声明方式是一致的：
一致

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +- `for` 循环会变成生成一个临时变量，一个 `for` 循环，以及一次 `buildArray(_:)` 方法调用。新的 `for` 循环遍历序列，将中间结果添加进数组中。临时数组会作为实参传递给 `buildArray(_:)` 调用。下面的声明方式是一致的：
会变成生成，明显不通顺。修改：对 `for` 循环来说，会生成一个临时……

同理一致

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +虽然转变行为是根据临时变量进行描述的，使用结果构造器并不会真的创建任何新的对你剩余代码可见的声明。
前半句不通顺，并且翻译的不正确，后半句太长，一遍读不懂，整句重新翻译。

2021-07-11 18:58 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +转换过程不会改变代码中的声明，这让使用临时常量或变量一步一步构造表达式成为可能。它也不会改变 `throw` 语句、编译时诊断语句，或包含 `return` 语句的闭包。
这让……成为可能，典型的直译，读起来不够通顺。改成：这样就可以使用……构造表达式。

2021-07-11 19:06 UTC, numbbbbb commented on source/03_language_reference/07_Attributes.md
> +虽然转变行为是根据临时变量进行描述的，使用结果构造器并不会真的创建任何新的对你剩余代码可见的声明。
后半句实际上也翻译错了。

2021-07-18 13:37 UTC, WAMaker commented
已修正有问题的翻译内容。

2021-07-19 01:58 UTC, merged