✨ `Extension` Translation
SwiftGGTeam/the-swift-programming-language-in-chinese pull request #1349
Opened 2024-08-10 12:36 UTC by Saafo

close #1316

2024-08-10 17:14 UTC, zhangqifan requested changes

2024-08-10 17:14 UTC, zhangqifan commented on swift-6-beta.docc/LanguageGuide/Extensions.md
> +扩展可以为一个类添加新的便利构造器，但是它们不能为一个类添加新的指定构造器或析构器。
建议在便利构造器（convenience initializer）、指定构造器（designated initializer）和析构器（deinitializer）后添加对应英文作为解释。

2024-08-10 17:14 UTC, zhangqifan commented on swift-6-beta.docc/LanguageGuide/Extensions.md
> +这使你可以扩展其他类型以接受你自己的自定义类型作为初始化器参数，
将`初始化器`修改成`构造器`

2024-08-10 17:14 UTC, zhangqifan commented on swift-6-beta.docc/LanguageGuide/Extensions.md
> +下面的示例为 Swift 的 `Int` 类型添加了一个新的修改方法 `square`，它可以将原始值平方：
建议调整为：

“下面的示例为 Swift 的 `Int` 类型添加了一个新的可变方法 `square`，它可以计算原始值的平方：”

2024-08-10 17:14 UTC, zhangqifan commented on swift-6-beta.docc/LanguageGuide/Extensions.md
>  from the right of the number:
英文原文需要移除

2024-08-10 17:14 UTC, zhangqifan commented on swift-6-beta.docc/LanguageGuide/Extensions.md
> +具体来说，它表示数字是负的、零的还是正的。
建议调整为：

“具体来说，它表示数字是负数、零还是正数。”

2024-08-10 17:14 UTC, zhangqifan commented on swift-6-beta.docc/LanguageGuide/Extensions.md
> +现在，任意 `Int` 的值都可以使用这个嵌套枚举：
建议调整为：

“现在，这个嵌套枚举可以用于任何 `Int` 值：”

2024-08-12 05:32 UTC, Saafo commented on swift-6-beta.docc/LanguageGuide/Extensions.md
> +下面的示例为 Swift 的 `Int` 类型添加了一个新的修改方法 `square`，它可以将原始值平方：
这里我统一改成“变值方法”了哈

2024-08-12 17:08 UTC, zhangqifan commented on swift-6-beta.docc/LanguageGuide/Extensions.md
> +下面的示例为 Swift 的 `Int` 类型添加了一个新的修改方法 `square`，它可以将原始值平方：
LGTM

2024-08-12 17:09 UTC, merged