1318 languageguide  genericsmd translate
SwiftGGTeam/the-swift-programming-language-in-chinese pull request #1358
Opened 2024-08-15 03:13 UTC by zxc199

2024-08-25 07:26 UTC, TsnumiDC reviewed
辛苦酌情采纳

2024-08-25 07:26 UTC, TsnumiDC commented on swift-6-beta.docc/LanguageGuide/Generics.md
> +定义一个协议时，声明一个或多个关联类型作为协议定义的一部分将会非常有用。关联类型为协议中的某个类型提供了一个占位符名称，其代表的实际类型在协议被遵循时才会被指定。关联类型通过 associatedtype 关键字来指定。
associatedtype ->
`associatedtype`

2024-08-25 07:26 UTC, TsnumiDC commented on swift-6-beta.docc/LanguageGuide/Generics.md
> +定义一个协议时，声明一个或多个关联类型作为协议定义的一部分将会非常有用。关联类型为协议中的某个类型提供了一个占位符名称，其代表的实际类型在协议被遵循时才会被指定。关联类型通过 associatedtype 关键字来指定。
关联类型为协议中的某个类型提供了一个占位符名称
*关联类型*为协议中的某个类型提供了一个占位符名称

2024-08-25 07:26 UTC, TsnumiDC commented on swift-6-beta.docc/LanguageGuide/Generics.md
> +以下是上文中非泛型的 IntStack，通过遵循 Container 协议，修改后的版本：
原文Here's a version of the nongeneric `IntStack` type
from above,
adapted to conform to the `Container` protocol:

以下是上文中非泛型的 `IntStack`，依据<doc:Generics#Generic-Types> ，通过遵循 `Container` 协议，修改后的版本：

2024-08-25 07:26 UTC, TsnumiDC commented on swift-6-beta.docc/LanguageGuide/Generics.md
> +由于 Swift 的类型推断，
由于 Swift 的类型推断机制，

2024-08-25 07:26 UTC, TsnumiDC commented on swift-6-beta.docc/LanguageGuide/Generics.md
> +- `someContainer` 中的元素可以通过不等于操作符（!=）来检查它们是否相同。
!=
`!=`

2024-08-26 06:07 UTC, Maples7 requested changes
建议可以酌情处理，有一些前后翻译的一致性和符号的使用可以全篇替换一下以免遗漏。

2024-08-26 06:07 UTC, Maples7 commented on swift-6-beta.docc/LanguageGuide/Generics.md
>  <!--
群里讨论过，最后的 Beta Software 段落也可以翻译一下。

2024-09-19 06:39 UTC, merged