feat: 闭包翻译工作
SwiftGGTeam/the-swift-programming-language-in-chinese pull request #1367
Opened 2024-08-21 14:12 UTC by wang-jiaolong

2024-08-28 17:00 UTC, zhangqifan commented on swift-6-beta.docc/LanguageGuide/Closures.md
> +我们经常会*调用*采用自动闭包的函数，但是很少去*实现*这样的函数。例如，`assert（condition：message：file：line：）` 函数接受自动闭包作为它的 `condition` 和 `message` 参数; 其 `condition` 参数仅在 Debug 版本中计算，而其 `message` 参数仅在 `condition` 为 `false` 时计算。
*调用* 和 *实现* 前后各添加一个空格

2024-08-28 17:00 UTC, zhangqifan commented on swift-6-beta.docc/LanguageGuide/Closures.md
> +即使 `customersInLine` 数组的第一个元素被闭包内的代码删除，但在实际调用闭包之前，不会删除数组中的元素。如果从不调用闭包，则永远不会计算闭包内的表达式，这意味着永远不会删除数组元素。请注意，`customerProvider` 的类型不是 `String`，而是 `（） -> String` --- 一个返回字符串的没有参数的函数。
括号修改成英文

2024-08-28 17:01 UTC, zhangqifan commented on swift-6-beta.docc/LanguageGuide/Closures.md
> +上面列表中的 `serve（customer：）` 函数采用显式闭包，返回客户的名称。下面的 `serve（customer：）` 版本执行相同的操作，但是，它不是采用显式闭包，而是通过使用 `@autoclosure` 属性标记其参数的类型来进行自动闭合。现在，您可以调用该函数，就好像它采用 `String` 参数而不是闭包一样。该参数会自动转换为闭包，因为 `customerProvider
括号修改成英文

2024-08-28 17:01 UTC, zhangqifan commented on swift-6-beta.docc/LanguageGuide/Closures.md
> +上面列表中的 `serve（customer：）` 函数采用显式闭包，返回客户的名称。下面的 `serve（customer：）` 版本执行相同的操作，但是，它不是采用显式闭包，而是通过使用 `@autoclosure` 属性标记其参数的类型来进行自动闭合。现在，您可以调用该函数，就好像它采用 `String` 参数而不是闭包一样。该参数会自动转换为闭包，因为 `customerProvider
上面列表中的 `serve(customer:)` 函数接受一个显式的闭包，该闭包返回顾客的名字。下面的 `serve(customer:)` 版本执行相同的操作，但它不接受显式的闭包，而是通过将其参数类型标记为 `@autoclosure` 特性来接受一个自动闭包。现在你可以调用这个函数，就像它接受一个 `String` 参数而不是闭包一样。因为 `customerProvider` 参数的类型被标记为 `@autoclosure` 特性，所以参数会自动转换为闭包。

2024-08-28 17:02 UTC, zhangqifan commented on swift-6-beta.docc/LanguageGuide/Closures.md
> +在上面的代码中，`collectCustomerProviders（_：）` 函数将闭包追加到 `customerProviders` 数组中，而不是调用作为其 `customerProvider` 参数传递给它的闭包。数组是在函数的作用域之外声明的，这意味着数组中的闭包可以在函数返回后执行。因此 `customerProvider` 参数必须允许逃逸出函数的作用域。
将中文括号修改成英文

2024-08-31 04:52 UTC, wang-jiaolong commented on swift-6-beta.docc/LanguageGuide/Closures.md
> +*闭包*是自包含的函数代码块，可以在代码中被传递和使用。Swift 中的闭包类似于其他编程语言中的闭包、匿名函数、lambda和块。
get

2024-09-04 10:18 UTC, zhangqifan requested changes

2024-09-04 10:18 UTC, zhangqifan commented on swift-6-beta.docc/LanguageGuide/Closures.md
> +在这个例子中，变量 number 被初始化为闭包参数 number 的值，这样就可以在闭包内部修改这个值。（注意，函数和闭包的参数本身总是常量。）闭包表达式还指定了 String 作为返回类型，表明映射后的新数组将存储字符串类型的值。
这里的 number 和 String 也需要 code syntax 引用起来：`number` 和 `String`

2024-09-19 06:31 UTC, merged