Swift 6 beta translation
SwiftGGTeam/the-swift-programming-language-in-chinese pull request #1370
Opened 2024-08-23 12:28 UTC by Shinolr

#1337

2024-08-27 07:07 UTC, Maples7 requested changes
Comment 有点多，这篇也挺难翻的，可以酌情处理建议内容。

有些问题需要全局替换和修改。还有些部分机翻味儿有点浓使得读起来难以理解，建议以后机翻完后再至少通读一遍人工校对和审核一下。

Cheers!

2024-08-29 08:06 UTC, Shinolr commented on swift-6-beta.docc/ReferenceManual/Attributes.md
> +# 特性
文章里既有 attribute 也有 property，全文替换起来有些麻烦，就继续使用特性了。你觉得可以吗？

2024-08-29 08:17 UTC, Maples7 commented on swift-6-beta.docc/ReferenceManual/Attributes.md
> +# 特性
OK 赞同 @Shinolr

2024-09-03 11:05 UTC, Maples7 requested changes
大部分都 OK 了，主要是继续检查一下 attribute 跟 property 的「特性」和「属性」的翻译区分开不要混淆。

2024-09-03 11:12 UTC, Maples7 requested changes
另外两处「结构体」，需全局检查一遍。

2024-09-03 11:12 UTC, Maples7 commented on swift-6-beta.docc/ReferenceManual/Attributes.md
> +将此特性应用于类、结构、枚举或协议，以将该类型的实例视为可调用函数。该类型必须实现 `dynamicallyCall(withArguments:)` 方法和 `dynamicallyCall(withKeywordArguments:)` 方法中的至少一个或都实现。
结构体

2024-09-03 11:12 UTC, Maples7 commented on swift-6-beta.docc/ReferenceManual/Attributes.md
> +将此特性应用于结构、类或枚举声明，以表示它包含程序流程的顶级入口点。该类型必须提供一个不接受任何参数并返回 `Void` 的 `main` 类型函数。例如：
结构体

2024-09-03 15:20 UTC, Shinolr commented on swift-6-beta.docc/ReferenceManual/Attributes.md
> +对于一个属性包装器，*被呈现值*是一个可以让属性包装器用来暴露额外功能的第二个值。属性包装器类型的作者负责确定其被呈现值的含义，并定义被呈现值所暴露的接口。要从属性包装器中投射一个值，请在包装器类型上定义一个 `projectedValue` 实例属性。编译器通过在包装属性的名称前加上美元符号（`$`）来合成被呈现值的标识符——例如，`someProperty` 的被呈现值是 `$somePro
这一段应该是 projected value

2024-09-03 15:22 UTC, Shinolr commented on swift-6-beta.docc/ReferenceManual/Attributes.md
> +  在上面的代码中，`FutureText` 作为 `brokenDrawing` 类型的一部分出现，因为它是 DrawEither 泛型类型中的类型之一。如果在运行时 `FutureText` 不可用， 即使在该类型显式未被使用的情况下，这可能会导致你的程序崩溃。
原文也有空格。此处的缩进是为了保持 markdown 的 list 结构？

2024-09-03 15:22 UTC, Shinolr commented on swift-6-beta.docc/ReferenceManual/Attributes.md
> +  例如，如果你编写一个包含三个分支的 switch 语句，编译器将使用一个具有三个叶节点的二叉树。同样，因为从根节点到第二个 case 分支的路径是“第二个子节点”，然后是“第一个子节点”，所以该 case 分支变成了像 `buildEither(first: buildEither(second: ... ))` 这样的嵌套调用。以下声明是等效的：
原文也有空格。此处的缩进是为了保持 markdown 的 list 结构？

2024-09-03 15:26 UTC, Shinolr commented
有三处可以讨论一下，我在对应的 comment 下边添加了回复。剩下的都按要求改了。

2024-09-03 15:50 UTC, Maples7 commented on swift-6-beta.docc/ReferenceManual/Attributes.md
> +  在上面的代码中，`FutureText` 作为 `brokenDrawing` 类型的一部分出现，因为它是 DrawEither 泛型类型中的类型之一。如果在运行时 `FutureText` 不可用， 即使在该类型显式未被使用的情况下，这可能会导致你的程序崩溃。
明白了，没看到原文的缩进。 @Shinolr

2024-09-03 15:53 UTC, Maples7 commented on swift-6-beta.docc/ReferenceManual/Attributes.md
> +应用此特性可将自定义 GameplayKit 组件属性公开给 SpriteKit 编辑器 UI。应用此特性还意味着 `objc` 特性。
这里没改 @Shinolr

2024-09-03 15:54 UTC, Maples7 commented on swift-6-beta.docc/ReferenceManual/Attributes.md
> +你可以通过编写 `@` 符号，并在其后加上属性的名称以及属性接受的任何参数，来指定一个特性。
这里没改 @Shinolr

2024-09-03 16:00 UTC, Maples7 reviewed
已回复 @Shinolr ，另外前面那次 review 的 unresolved 的 comment 有遗漏未改的部分。已经确认修改好的我都 resolve 了。

2024-09-03 16:04 UTC, Maples7 commented on swift-6-beta.docc/ReferenceManual/Attributes.md
> +描述 `main` 属性要求的另一种方法是，属性作用于的类型必须满足与遵循以下假设协议的类型相同的要求：
第二个「属性」也应为「特性」。

2024-09-04 01:26 UTC, Maples7 approved these changes

2024-09-19 06:28 UTC, merged