Translate 1341 lexical structure from English to Chinese
SwiftGGTeam/the-swift-programming-language-in-chinese pull request #1376
Opened 2024-08-27 14:29 UTC by Maples7

Close #1341

2024-09-04 10:08 UTC, zhangqifan requested changes
总体很流畅，我用 Claude 过了一遍，基本上没有什么问题

2024-09-04 10:08 UTC, zhangqifan commented on swift-6-beta.docc/ReferenceManual/LexicalStructure.md
> +自定义运算符可以用这些 ASCII 字符之一开头：`/`、`=`、`-`、`+`、`!`、`*`、`%`、`<`、`>`、`&`、`|`、`^`、`?` 或 `~`，或者是定义在下面语法中的 Unicode 字符（其中包括来自 *Mathematical Operators*、*Miscellaneous Symbols* 和 *Dingbats* Unicode 块的字符等）之一。在第一个字符
...（其中包括来自 *数学运算符*（Mathematical Operators）、*杂项符号*（Miscellaneous Symbols）和 *装饰符号*（Dingbats）Unicode 块的字符等）之一。在第一个字符之后，还允许使用组合 Unicode 字符（Combining Unicode Character）。

2024-09-04 14:29 UTC, Maples7 commented on swift-6-beta.docc/ReferenceManual/LexicalStructure.md
> +自定义运算符可以用这些 ASCII 字符之一开头：`/`、`=`、`-`、`+`、`!`、`*`、`%`、`<`、`>`、`&`、`|`、`^`、`?` 或 `~`，或者是定义在下面语法中的 Unicode 字符（其中包括来自 *Mathematical Operators*、*Miscellaneous Symbols* 和 *Dingbats* Unicode 块的字符等）之一。在第一个字符
已修改，感谢 review🙏 @zhangqifan

2024-09-05 01:57 UTC, zhangqifan approved these changes

2024-09-05 01:57 UTC, merged