1335: feat：翻译完 1335 Type Casting⭐️⭐️⭐️⭐️
SwiftGGTeam/the-swift-programming-language-in-chinese pull request #1377
Opened 2024-08-28 10:32 UTC by hdmdhr

原文地址：https://docs.swift.org/swift-book/documentation/the-swift-programming-language/typecasting/

Closes: #1335

2024-09-22 13:13 UTC, yongfrank commented
@Shinolr @brooklyn1999 有空请帮忙 Review Thx!

2024-09-27 14:57 UTC, Pancf requested changes

2024-09-27 14:57 UTC, Pancf commented on swift-6-beta.docc/LanguageGuide/TypeCasting.md
> +为了解决这个问题，上面的示例使用了可选绑定来检查可选 `Movie` 是否实际包含一个值（也就是说，找出向下转型是否成功。）
括号里的建议改成“即，检查向下转型是否成功”

2024-09-27 14:57 UTC, Pancf commented on swift-6-beta.docc/LanguageGuide/TypeCasting.md
> +Swift 为处理非特定类型提供了两种特殊类型：
nonspecific types译为通用类型感觉更合适

2024-09-27 14:57 UTC, Pancf commented on swift-6-beta.docc/LanguageGuide/TypeCasting.md
> +以及一个接收字符串值并返回另一个字符串值的闭包表达式。
既然前面的`String`都保留了，闭包这里也保留吧

2024-09-27 14:57 UTC, Pancf commented on swift-6-beta.docc/LanguageGuide/TypeCasting.md
> +`things` 数组包含两个 `Int` 值、两个 `Double` 值、一个 `String` 值、一个类型为 `(Double, Double)` 的元组、电影 “捉鬼敢死队”，
这里不要直译“电影捉鬼敢死队”，可以是“`movie`实例”，名称翻不翻无所谓

2024-09-27 14:57 UTC, Pancf commented on swift-6-beta.docc/LanguageGuide/TypeCasting.md
> +如果常量或变量的已知类型是 `Any` 或 `AnyObject`，要确定其具体类型，可以在 switch 语句的情况下使用 `is` 或 `as` 模式。
switch-case中的case不应该翻译，应保留

2024-09-27 14:57 UTC, Pancf commented on swift-6-beta.docc/LanguageGuide/TypeCasting.md
> +该 `switch` 语句的一些情况将其匹配值与指定类型的常量绑定，以便打印其值：
case同上

2024-09-27 14:57 UTC, Pancf commented on swift-6-beta.docc/LanguageGuide/TypeCasting.md
> +> 如果您确实需要将可选值用作 `Any` 值，可以使用 `as` 操作符显式地将可选值转换为 `Any` 值，如下所示。
“您”->“你”

2024-10-10 12:26 UTC, hdmdhr commented on swift-6-beta.docc/LanguageGuide/TypeCasting.md
> +具体来说，它声明了一个字符串类型的 `name` 属性和一个 `init(name:)` 初始化器。
- 初始化器先保留了，最后看组织决定是用“构造器”还是“初始化器”。
- 除非是遇到翻译过来造成不通顺的情况，`String` 这种关键字尽量保留吧

2024-10-10 12:37 UTC, hdmdhr commented on swift-6-beta.docc/LanguageGuide/TypeCasting.md
> +类似的原理也用于检查 `Song` 实例，并在库中找到歌曲时打印适当的描述（包括艺术家姓名）。
改为“并在从资源库中找到歌曲时…”

2024-10-10 12:41 UTC, hdmdhr commented on swift-6-beta.docc/LanguageGuide/TypeCasting.md
> +`things` 数组包含两个 `Int` 值、两个 `Double` 值、一个 `String` 值、一个类型为 `(Double, Double)` 的元组、电影 “捉鬼敢死队”，
我觉着这里可以用译名吧，因为原文用的不是字符串的直立引号""，我觉得翻译出来更容易读者理解（和安利）。

2024-10-10 14:01 UTC, yongfrank commented
@Pancf 可以再看一眼，没问题就 Approve Merge, Thx!

2024-10-15 01:00 UTC, merged