1338 referencemanual declarations
SwiftGGTeam/the-swift-programming-language-in-chinese pull request #1380
Opened 2024-09-04 03:18 UTC by Shinolr

close #1338

2024-10-14 12:51 UTC, saitjr requested changes

2024-10-14 12:51 UTC, saitjr commented on swift-6-beta.docc/ReferenceManual/Declarations.md
> +函数参数是一个以逗号分隔的列表，其中每个参数都有几种形式之一。在函数调用中，参数的顺序必须与函数声明中的参数顺序匹配。参数列表中最简单的项具有以下形式：
- 原文：函数参数是一个以逗号分隔的列表，其中每个参数都有几种形式之一
- 建议：函数的参数是一个以逗号分隔的列表，每个参数都可以是不同的类型。

2024-10-14 12:51 UTC, saitjr commented on swift-6-beta.docc/ReferenceManual/Declarations.md
> +函数参数是一个以逗号分隔的列表，其中每个参数都有几种形式之一。在函数调用中，参数的顺序必须与函数声明中的参数顺序匹配。参数列表中最简单的项具有以下形式：
- 原文：在函数调用中，参数的顺序必须与函数声明中的参数顺序匹配。参数列表中最简单的项具有以下形式：
- 建议：函数调用时的参数顺序必须和函数声明时的参数顺序一致。最简单的参数列表有着如下的形式：

2024-10-14 12:51 UTC, saitjr commented on swift-6-beta.docc/ReferenceManual/Declarations.md
> +一个参数有一个名称，在函数体内使用，以及一个实参标签，在调用函数或方法时使用。默认情况下，参数名称也用作实参标签。例如：
建议：参数有名称和标签，名称用于在函数内访问参数，标签用于在调用函数时指定参数。默认情况下，参数的名称也可以作为标签。例如：

2024-10-16 02:04 UTC, yongfrank commented
@saitjr 这篇已经改好了

2024-10-16 16:50 UTC, saitjr commented on swift-6-beta.docc/ReferenceManual/Declarations.md
> +`borrowing` 修饰符表示函数不会保留参数的值。在这种情况下，调用者保持对对象的所有权，并负责对象的生命周期管理。使用 `borrowing` 可以在函数只临时使用对象时，最大限度地减少开销。
`borrowing` 修饰函数参数时，函数不会保留参数的值。在这种情况下，调用者保留对象的所有权，并负责对象的生命周期管理。所以当函数只是临时使用对象时，用 `borrowing` 修饰可以最大限度地减少开销。

2024-10-16 16:50 UTC, saitjr commented on swift-6-beta.docc/ReferenceManual/Declarations.md
> +// 如上所述，但这个 `isLessThan` 还需要记录最小值
// 同样是 `isLessThan` 函数，这个 `isLessThan` 可以将最小值记录下来

2024-10-16 16:50 UTC, saitjr commented on swift-6-beta.docc/ReferenceManual/Declarations.md
> +// 通常，这是你对一个值执行的最后一件事
// 通常，这就是最后一次使用 value 了

2024-10-16 16:50 UTC, saitjr commented on swift-6-beta.docc/ReferenceManual/Declarations.md
> +#### 借用和消耗参数
#### 借用和消费参数

2024-10-16 16:50 UTC, saitjr commented on swift-6-beta.docc/ReferenceManual/Declarations.md
> +store(a: someValue)  // 此函数消耗 someValue
store(a: someValue) // 此函数消费 someValue

2024-10-16 16:50 UTC, saitjr commented on swift-6-beta.docc/ReferenceManual/Declarations.md
> +参数可以通过以下形式被忽略、接受可变数量的值，以及提供默认值：
参数可以被忽略，数量可以不固定，还可以为其提供默认值，使用形式如下：

2024-10-20 16:14 UTC, saitjr approved these changes

2024-10-20 16:14 UTC, saitjr commented on swift-6-beta.docc/ReferenceManual/Declarations.md
> +函数的类型包括它是否会抛出错误以及它抛出的错误类型。这个子类型关系意味着，例如，你可以在需要抛出错误的上下文中使用不抛出错误的函数。有关抛出错误函数类型的更多信息，请参阅 <doc:Types#Function-Type>。有关处理具有显式类型的错误的示例，请参阅 <doc:ErrorHandling#Specifying-the-Error-Type>。
函数的类型包括：它是否会抛出错误，以及它抛出的错误类型。非抛出函数是抛出函数的子类型。所以，可以在使用抛出函数的地方使用非抛出函数。有关抛出错误函数类型的更多信息，请参阅 <doc:Types#Function-Type>。有关处理具有显式类型的错误的示例，请参阅 <doc:ErrorHandling#Specifying-the-Error-Type>。

2024-10-20 16:15 UTC, saitjr commented
剩一个选择性修复的评论，已经 Approve 了

2024-10-20 16:28 UTC, yongfrank commented
@Shinolr 可以再看一眼👀

2024-10-21 03:27 UTC, saitjr approved these changes

2024-10-21 03:42 UTC, merged