1329:Translation for LanguageGuide / optional-chaining.md ⭐️⭐️⭐️⭐️⭐️
SwiftGGTeam/the-swift-programming-language-in-chinese pull request #1387
Opened 2024-09-23 08:14 UTC by MOXCOOT

Translation for LanguageGuide / optional-chaining

2024-10-06 04:24 UTC, Channe requested changes
我换一篇没有认领的来 Review

2024-10-06 04:24 UTC, Channe commented on swift-6-beta.docc/LanguageGuide/OptionalChaining.md
> -Access members of an optional value without unwrapping.
此句未翻译

2024-10-14 15:00 UTC, saitjr requested changes

2024-10-14 15:00 UTC, saitjr commented on swift-6-beta.docc/LanguageGuide/OptionalChaining.md
> +特别地，可选链式调用的返回结果与原本的返回结果具有相同的类型，但是被包装成了一个可选值。例如，使用可选链式调用访问属性，当可选链式调用成功时，如果属性原本的返回结果是 `Int` 类型，则会变为 `Int?` 类型。
具体来说，可选链调用的结果，除了被包装成了一个可选值外，类型与预期的返回值类型是相同的。例如，正常情况下返回 `Int` 的属性，在通过可选链访问时，返回的是 `Int?`。

2024-10-14 15:00 UTC, saitjr commented on swift-6-beta.docc/LanguageGuide/OptionalChaining.md
> +下面几段代码将解释可选链式调用和强制展开的不同。
下面几段代码将演示可选链式调用和强制展开的不同，以及如何判断可选链是否调用成功。

2024-10-14 15:00 UTC, saitjr commented on swift-6-beta.docc/LanguageGuide/OptionalChaining.md
> +	var residence: Residence?
这里为什么把四个空格，换成了 Tab？

2024-10-14 15:00 UTC, saitjr commented on swift-6-beta.docc/LanguageGuide/OptionalChaining.md
> +假如你创建了一个新的 `Person` 实例,它的 `residence` 属性由于是是可选型而将初始化为 `nil`,在下面的代码中,`john` 有一个值为 `nil` 的 `residence` 属性：
这一句的逗号有问题，注意用中文逗号

2024-10-14 15:00 UTC, saitjr commented on swift-6-beta.docc/LanguageGuide/OptionalChaining.md
> +假如你创建了一个新的 `Person` 实例,它的 `residence` 属性由于是是可选型而将初始化为 `nil`,在下面的代码中,`john` 有一个值为 `nil` 的 `residence` 属性：
假如你创建了一个新的 `Person` 实例，由于 `residence` 属性是可选型，所以初始值是 `nil`。就像下面的代码中，`john` 有一个值为 `nil` 的 `residence` 属性：

2024-10-14 15:00 UTC, saitjr commented on swift-6-beta.docc/LanguageGuide/OptionalChaining.md
> +如果使用叹号（`!`）强制展开获得这个 `john` 的 `residence` 属性中的 `numberOfRooms` 值，会触发运行时错误，因为这时 `residence` 没有可以展开的值：
如果使用叹号（`!`）对 `john` 的 `residence` 属性中的 `numberOfRooms` 值强制解包，会触发运行时错误，因为这时 `residence` 没有可以解包的值：

2024-10-20 13:43 UTC, saitjr requested changes

2024-10-20 13:43 UTC, saitjr commented on swift-6-beta.docc/LanguageGuide/OptionalChaining.md
> +	print("John's residence has \(roomCount) room(s).")
这个地方，原文不是只打印了一次吗？怎么有两个 print

2024-10-20 13:43 UTC, saitjr commented on swift-6-beta.docc/LanguageGuide/OptionalChaining.md
> +`john.residence` 现在包含一个实际的 `Residence` 实例，而不再是 `nil`。如果你试图使用先前的可选链式调用访问 `numberOfRooms`，它现在将返回值为 `1` 的 `Int?` 类型的值：
这里也是，为啥有两句

2024-10-20 13:43 UTC, saitjr commented on swift-6-beta.docc/LanguageGuide/OptionalChaining.md
>  ```
这三个 ```，搞错地方了吧。是不是这个文件解冲突解出问题了

2024-10-20 15:47 UTC, saitjr approved these changes

2024-10-20 16:30 UTC, merged