Swift 6 Generic Parameters and Arguments 的翻译
SwiftGGTeam/the-swift-programming-language-in-chinese pull request #1395
Opened 2024-10-06 07:15 UTC by brooklyn1999

在原5.7 的翻译中，Generic Parameters 都翻译为“泛型形参”，在这版翻译中，我除了在开头有区分形参和实参，在后面的 Generic Parameters 中用的都是“泛型参数”，麻烦 Reviewer 辨析一下哪个用法更好一点，谢谢！

2024-10-13 17:20 UTC, Channe requested changes
建议区分翻译 parameter 和 argument，否则容易混淆，只能看原文才能明白

2024-10-13 17:20 UTC, Channe commented on swift-6-beta.docc/ReferenceManual/GenericParametersAndArguments.md
> +你可以通过对类型参数提供不同的约束、要求或两者来重载泛型函数或构造器。当你调用重载的泛型函数或构造器时，编译器会使用这些约束来决定调用哪个重载的函数或构造器。
重载泛型函数或构造器，需要在泛型形参子句中的类型形参必须有不同的约束或要求。

2024-10-13 17:20 UTC, Channe commented on swift-6-beta.docc/ReferenceManual/GenericParametersAndArguments.md
>  > *generic-parameter-clause* → **`<`** *generic-parameter-list* **`>`** \
语法部分建议翻译

2024-10-13 17:20 UTC, Channe commented on swift-6-beta.docc/ReferenceManual/GenericParametersAndArguments.md
> +你还可以用本身就是泛型类型的特定版本的类型实参替代类型参数（假设已满足合适的约束和关联类型要求）。例如，你可以将 `Array<Element>`中的类型参数 `Element` 替换为 `Array<Int>` 的专用版本，以形成一个元素本身是整数数组的数组。
还可以用本身是泛型类型的特定版本的类型实参替代类型形参（假设已满足合适的约束和关联类型要求）。例如，可以将 `Array<Element>`中的类型形参 `Element` 替换为 Array 泛型专用版本 `Array<Int>` ，以形成一个元素本身是整数数组的二维数组。

2024-10-13 17:20 UTC, Channe commented on swift-6-beta.docc/ReferenceManual/GenericParametersAndArguments.md
> +正如在<doc:GenericParametersAndArguments#Generic-Parameter-Clause>中提到的，你在指定泛型函数或构造器的类型实参时，不能使用泛型实参子句来指定泛型函数或构造器的类型实参。
在指定泛型函数或构造器的类型实参时，不能使用泛型实参子句。

2024-10-14 09:19 UTC, yongfrank commented
@brooklyn1999 可以采纳合理的 Comment

2024-10-16 15:08 UTC, yongfrank commented
@Channe 可以看看没问题就 approve merge Thx

2024-10-17 06:01 UTC, merged